<?php
// api/config.example.php
// Copy to api/config.php and fill in real values for local development.
// In production this file is generated by GitHub Actions from Secrets.

define('DB_HOST',        'localhost');
define('DB_NAME',        'your_db_name');
define('DB_USER',        'your_db_user');
define('DB_PASS',        'your_db_password');
define('SESSION_SECRET', 'your-random-secret-64-chars');
define('MAIL_FROM',      'noreply@yourdomain.cz');
define('APP_URL',        'https://board.besix.cz');

// ─── The rest is identical to config.php ───────────────────────────────────
ini_set('session.cookie_httponly', 1);
ini_set('session.cookie_samesite', 'Lax');
session_name('BESIX_SESS');
if (session_status() === PHP_SESSION_NONE) session_start();

$allowed = [APP_URL, 'http://localhost', 'http://127.0.0.1'];
$origin  = $_SERVER['HTTP_ORIGIN'] ?? '';
if (in_array($origin, $allowed, true)) {
    header('Access-Control-Allow-Origin: ' . $origin);
    header('Access-Control-Allow-Credentials: true');
}
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, X-Requested-With');
header('Content-Type: application/json; charset=UTF-8');
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit; }

function getDB(): PDO {
    static $pdo = null;
    if ($pdo !== null) return $pdo;
    $dsn = 'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=utf8mb4';
    $pdo = new PDO($dsn, DB_USER, DB_PASS, [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES   => false,
    ]);
    return $pdo;
}
function jsonResponse(array $data, int $code = 200): never {
    http_response_code($code); echo json_encode($data, JSON_UNESCAPED_UNICODE); exit;
}
function requireAuth(): array {
    if (empty($_SESSION['user_id'])) jsonResponse(['error' => 'Nejsi přihlášen'], 401);
    $stmt = getDB()->prepare('SELECT id,name,email,avatar_color FROM users WHERE id=?');
    $stmt->execute([$_SESSION['user_id']]);
    $u = $stmt->fetch();
    if (!$u) { session_destroy(); jsonResponse(['error' => 'Uživatel nenalezen'], 401); }
    return $u;
}
function requireProjectRole(int $projectId, string $minRole): array {
    $user = requireAuth();
    $roles = ['viewer'=>0,'member'=>1,'admin'=>2,'owner'=>3];
    $stmt = getDB()->prepare('SELECT pm.role FROM project_members pm JOIN projects p ON p.id=pm.project_id WHERE pm.project_id=? AND pm.user_id=? AND p.is_active=1');
    $stmt->execute([$projectId, $user['id']]);
    $row = $stmt->fetch();
    if (!$row || ($roles[$row['role']]??-1) < ($roles[$minRole]??99)) jsonResponse(['error'=>'Nemáš oprávnění'],403);
    return array_merge($user, ['role' => $row['role']]);
}
function sanitize(string $v): string { return htmlspecialchars(trim($v), ENT_QUOTES, 'UTF-8'); }
function getBody(): array { return json_decode(file_get_contents('php://input'), true) ?? []; }
